baseURL: 'https://blog.pwntools.com/'
languageCode: en-us
title: Pwntools Blog

theme: beautifulhugo
# theme: PaperMod

PygmentsCodeFences: true
PygmentsUseClasses: true

PygmentsUseClassic: false

blackfriday:
  plainIDAnchors: true

markup:
  tableOfContents:
    endLevel: 1
    ordered: false
    startLevel: 1


params:
  homeInfoParams:
    Title: 'Hi there :wave:'
    Content: 'Can be Info, links, about...'

